blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/MudBlazor/MudBlazor/discussions
    about: Please ask and answer questions here
  - name: Discord
    url: https://discord.gg/mudblazor
    about: You can also ask and answer questions here