name: net6-ci

on:
  push:
    branches: [ net6 ]
  pull_request:
    branches: [ net6 ]
  workflow_dispatch:
    

jobs:
  pipeline:
    name: Pipeline
    uses: MudBlazor/MudBlazor/.github/workflows/template-pipeline.yml@net6
    with:
      dotnet-version: 6.0.x
      dotnet-prerelease: true
      publish-coverage: true
      deploy-web-app: true
      deploy-condition: 'refs/heads/net6'
      deploy-web-app-name: mudblazor-net6
    secrets:
      publish-profile: ${{ secrets.PUBLISH_MUDBLAZOR_NET6 }}
